fix: load external app
InseeFr/Drama-Queen pull request #268
Opened 2024-11-12 08:12 UTC by laurentC35

2024-11-12 10:33 UTC, QRuhier approved these changes
a bit less clear, but no better solution

2024-11-13 08:54 UTC, chloe-renaud reviewed
Wouldn't it be better to use this solution with a useEffect that does a cleanup in the end?
https://stackoverflow.com/a/34425083
Or this hook: https://react-hooked.vercel.app/docs/useScript

2024-11-15 10:50 UTC, EmmanuelDemey approved these changes

2024-11-15 15:18 UTC, chloe-renaud requested changes
Wouldn't it be better to use this solution with a useEffect that does a cleanup in the end?
See: https://react-hooked.vercel.app/docs/useScript

2024-11-18 13:37 UTC, merged